kind: pipeline
name: default

steps:
  - name: backend
    depends_on: [ clone  ]
  - name: frontend
    depends_on: [ clone  ]
  - name: app
    depends_on: [ backend, frontend ]
  - name: unit-test
    depends_on: [ app ]
  - name: it-test
    privileged: true
    depends_on: [ app ]

