version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
      - ../:/var/www/html
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - php
    ports:
      - "8080:80"

  php:
    image: ${APP_IMAGE}
    build:
      context: ../
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ~/.cache/docker-composer:/var/www/.composer
    depends_on:
      - mysql
    env_file:
      - ../.env
    ports:
      - "9000:9000"

  mysql:
    image: ${APP_NAME}/mysql:5.7.17
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
        - ../database:/docker-entrypoint-initdb.d
        - portal_database:/var/lib/mysql
        - ../:/var/www/html

volumes:
  portal_database:
    external: true

# vim: tabstop=2:softtabstop=0:expandtab:shiftwidth=2:smarttab
