version: '3'
services:
  ingress:
    image: nginx:latest
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
      - ../:/var/www/html
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "127.0.0.1:80:80"

  application:
    image: example:latest
    env_file:
      - ../.env
    ports:
      - "127.0.0.1:9000:9000"

  db:
    image: postgres:9.6-alpine3.14
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "ciuser"
      POSTGRES_DB: "portal"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
        - ../:/var/www/html

  pipeline:
    image: drone/drone:2.4.0
    ports:
      - 8080:80
    volumes:
      - /var/lib/drone:/data
    env_file:
      - ./drone.env

  pipelinedb:
    image: postgres:9.6-alpine3.14
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "drone"
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
        - ../:/var/www/html

  eartlhy-runner:
    image: 18392019228/drone-runner-earthly:main3
    ports:
      - 3000
    depends_on:
      - pipeline
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./drone.env


# vim: tabstop=2:softtabstop=0:expandtab:shiftwidth=2:smarttab
